#!/bin/sh

event=$(khal list -a "Personal Calendar" today 3d --day-format ""  --format "{title}")

if [ "$event" != "No events" ] 
then
      khal list -a "Personal Calendar" today 3d --day-format ""  --format "{title}"
fi
